version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouseDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    image: warehouse_app
    container_name: warehouse_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouseDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
